### ISSUE TITLE
Unable to Manually Select and Input Number into OTP Fields Other than the First Field

### ISSUE THREAD

**Issue by apachi1444** [anday013/react-native-otp-entry#65]
**Describe the bug**
Users cannot manually select and input a number into a text input field other than the first one when using the OTP library. This issue prevents users from correcting or modifying any number except the first in the sequence.

**Expected behavior**
Users should be able to manually select any text input field within the OTP input sequence and input a number directly into the selected field. The focus should remain on the chosen input field until the user navigates to a different one or completes the OTP input process.

**Comment by anday013** [comment]
Hi, @apachi1444 , thank you for raising this question. UX of OTP style inputs are a bit different than normal Text Inputs, as each character divided into separate blocks. So, long story short, it's a bit tricky in terms of proper UX to correct or modify previous character(s), and because generally, the otp codes are short, it's acceptable for a user to backspace till the correction point.

One other suggestion can be, when user taps on already filled blocks, it removes the character with the ones that follow it, so the user gets a chance to correct and retype from that place

**Comment by anday013** [comment]
Closing this ticket due to inactivity. Feel free to reopen it

**Comment by apachi1444** [comment]
Hello anday , sorry for this late reply
I just retested the problem and I remark even if I don't type anything and I want to start from the 3rd character for example , it blocks me
